#!/usr/bin/env bash

PATH="$HOME/.config/bspwm/scripts:$PATH"

# Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1 

# Fix startx ( Auto login )
export WM="bspwm"

# Fix KDE THEME
export QT_QPA_PLATFORMTHEME=qt5ct

# Workspaces
for monitor in "$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)"; do
	bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
done

# bspwm config
bspc config external_rules_command 		"$HOME"/.config/bspwm/scripts/ExternalRules

bspc config remove_unplugged_monitors 	true
bspc config remove_disabled_monitors 	true
bspc config border_width 				0
bspc config border_radius 				10
bspc config window_gap 					6
bspc config focus_follows_pointer 		true
bspc config split_ratio					0.51
bspc config single_monocle 				true
bspc config borderless_monocle 			false
bspc config gapless_monocle 			false
bspc config normal_border_color 		"#101010"
bspc config focused_border_color        "#f8f8f6"
bspc config pointer_modifier			mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner


# Terminate already running polybar, sxhkd and dunst instances
processes=("polybar" "sxhkd" "dunst" "conky" "picom")
for process in "${processes[@]}"; do
	if pgrep -f "$process"; then
		pkill -9 -f "$process" > /dev/null; sleep 0.1
	fi
done

# Start sxhkd
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Display
Display

# Wallpaper
feh --no-fehbg --bg-fill "$HOME"/.dotfiles/wallpaper/wall_03.jpg

# conky 
conky -c "$HOME"/.config/bspwm/conky.conf &

# Compositor
picom --config "$HOME"/.config/bspwm/picom.conf &

# Enable numlock
numlockx on &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Notification
dunst --config "$HOME"/.config/dunst/dunstrc &

# Autolock
xss-lock -- betterlockscreen -l &

# Ibus daemon
ibus-daemon -drx &

# Generate lockscreen wallpaper
betterlockscreen -u "$HOME"/.dotfiles/wallpaper/wall_03.jpg

# Other
xsetroot -cursor_name left_ptr
