#!/usr/bin/env bash

DISPLAY=":0"  # Set the DISPLAY environment variable to your X session, e.g., :0
MONITER="DP1"

if ! xrandr --query | grep "1920x1080"; then
  xrandr --newmode "1920x1080" 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync
  xrandr --addmode "$MONITER" "1920x1080"
fi

xrandr --output "$MONITER" --mode "1920x1080"
