#!/usr/bin/env zsh

dependencies=(alacritty bspwm dragon-drop dunst maim feh git gtk-engine-murrine gvfs gvfs-afc gvfs-mtp gvfs-smb htop firefox lxappearance vlc neovim networkmanager pamixer pavucontrol ranger rofi scrot sed sxhkd udisks2 ttf-roboto-mono ttf-maple ttf-jetbrains-mono-nerd ttf-ubuntu-font-family ttf-ubuntu-nerd ttf-roboto-mono-nerd unzip xclip xdg-user-dirs-gtk xorg-xinit zathura zathura-pdf-mupdf zip picom-simpleanims-next-git zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting dolphin qt5ct kvantum kde-cli-tools)
configs=( "bspwm" "alacritty" "ranger" "dunst" "neofetch" "htop" "zathura" )
files=( ".zshrc" ".xinitrc" ".Xresources" ".ssh" ".gitconfig" ".gnupg" )

homeLink() {
    for file in "${files[@]}"; do
        ln -s "$HOME/.dotfiles/home/$file" "$HOME/"
    done
}

configLink() {
    for config in "${configs[@]}"; do
        ln -s "$HOME/.dotfiles/config/$config" "$HOME/.config/"
    done
}

dependenciesCheck(){
    for pkg in "${dependencies[@]}"; do
        if ! paru -Qi "$pkg" &>/dev/null; then
            paru -S --noconfirm "$pkg"
        fi
    done
}

# Perform git pull 
cd $HOME/.dotfiles/ && git pull && cd $HOME/

# Check if git pull was successful
if [ $? -eq 0 ]; then
    dependenciesCheck
fi
